# Generated by Django 4.2 on 2023-06-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_alter_produkitem_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('C', 'Cleanser'), ('T', 'Toner'), ('S', 'Serum'), ('M', 'Moisturizer'), ('P', 'Protection')], max_length=2),
        ),
    ]
