# Generated by Django 4.2 on 2023-06-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0010_alter_produkitem_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
